/// Flutter icons ButtonArrow
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ButtonArrow
///      fonts:
///       - asset: fonts/ButtonArrow.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class ButtonArrow {
  ButtonArrow._();

  static const _kFontFam = 'ButtonArrow';
  static const String? _kFontPkg = null;

  static const IconData buttonarrowleft = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buttonarrowright = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
