// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSHfE6oJbSVbuQ1d4q-AdS7uXCN56Vi18',
    appId: '1:460677981430:web:6ecbda45fa96e7d36fb8d7',
    messagingSenderId: '460677981430',
    projectId: 'fun-letters-4aa81',
    authDomain: 'fun-letters-4aa81.firebaseapp.com',
    storageBucket: 'fun-letters-4aa81.appspot.com',
    measurementId: 'G-TWWH8NKXF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0eeLFBJ13QbKtEFWKuqCMmdFHa-F8kTI',
    appId: '1:460677981430:android:e592865314d4c14b6fb8d7',
    messagingSenderId: '460677981430',
    projectId: 'fun-letters-4aa81',
    storageBucket: 'fun-letters-4aa81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuSVz8PNqB9S2-5d7XVWK-xjETV5au4vc',
    appId: '1:460677981430:ios:f3f6d4d446405d5c6fb8d7',
    messagingSenderId: '460677981430',
    projectId: 'fun-letters-4aa81',
    storageBucket: 'fun-letters-4aa81.appspot.com',
    iosBundleId: 'com.example.wist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuSVz8PNqB9S2-5d7XVWK-xjETV5au4vc',
    appId: '1:460677981430:ios:f3f6d4d446405d5c6fb8d7',
    messagingSenderId: '460677981430',
    projectId: 'fun-letters-4aa81',
    storageBucket: 'fun-letters-4aa81.appspot.com',
    iosBundleId: 'com.example.wist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSHfE6oJbSVbuQ1d4q-AdS7uXCN56Vi18',
    appId: '1:460677981430:web:6759cd4e91be68de6fb8d7',
    messagingSenderId: '460677981430',
    projectId: 'fun-letters-4aa81',
    authDomain: 'fun-letters-4aa81.firebaseapp.com',
    storageBucket: 'fun-letters-4aa81.appspot.com',
    measurementId: 'G-YPDHT5C7SL',
  );
}
