/// Flutter icons My_Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_Icons
///      fonts:
///       - asset: fonts/My_Icons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
library;
import 'package:flutter/widgets.dart';


// ignore: camel_case_types
class My_Icons {
  My_Icons._();

  static const _kFontFam = 'MyIcons';
  static const _kFontFam1 = 'Arrow';
  static const _kFontFam2 = 'ButtonArrow';
  static const String? _kFontPkg = null;

  static const IconData next = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows = IconData(0xe809, fontFamily:_kFontFam1 , fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buttonarrowleft = IconData(0xe80a, fontFamily: _kFontFam2, fontPackage: _kFontPkg);
  static const IconData buttonarrowright = IconData(0xe80b, fontFamily: _kFontFam2, fontPackage: _kFontPkg);

}
